[global]
# directory of test results
results = /home/eda230201/checking_results

# cases to be tested
case_dir = /home/public/benchmark_final_1207/benchmark_all

# flow: ifpga(default), balance, rewrite, refactor
flow = eda23 

# path of run.sh
bin = /home/chfeng/bin

# path of imap
imap = /home/public/iMAP/bin

